const colors = {
  light: {
    text: "#080e1a",
    tint: "#eb9100",
    background: "#f0f4ff",
    foreground: "#080e1a",
    card: "#ffffff",
    cardForeground: "#080e1a",
    primary: "#eb9100",
    primaryForeground: "#ffffff",
    secondary: "#e8edf8",
    secondaryForeground: "#080e1a",
    muted: "#e5e8ef",
    mutedForeground: "#6b7a9e",
    accent: "#fff3e0",
    accentForeground: "#eb9100",
    destructive: "#e81515",
    destructiveForeground: "#ffffff",
    border: "#dde3f0",
    input: "#dde3f0",
    success: "#16a34a",
    warning: "#f59e0b",
  },
  dark: {
    text: "#f8fafc",
    tint: "#ffcc00",
    background: "#080e1a",
    foreground: "#f8fafc",
    card: "#0d1524",
    cardForeground: "#f8fafc",
    primary: "#eb9100",
    primaryForeground: "#ffffff",
    secondary: "#1a2540",
    secondaryForeground: "#f8fafc",
    muted: "#1e2a3d",
    mutedForeground: "#6b7a9e",
    accent: "#2a1f00",
    accentForeground: "#ffcc00",
    destructive: "#e81515",
    destructiveForeground: "#ffffff",
    border: "#1a2540",
    input: "#1a2540",
    success: "#22c55e",
    warning: "#f59e0b",
  },
  radius: 6,
};

export default colors;
